#!/usr/bin/sh

echo ----------------------------------------------------------------
echo ----------------------------------------------------------------
cat documentation.txt
echo ----------------------------------------------------------------
echo Running Make
make
echo
echo
echo ----------------------------------------------------------------
echo Testing with Correct SIC Assembly
./project2 /Test/test21.sic

echo ----------TEST 21 Object File-------------------------------------------
less /Test/test21.sic.obj
echo ----------------------------------------------------------------
echo Testing case 2  SIC Program to copy a string using indexed addressing
./project2 /Test/test22.sic
echo ----------TEST 22 Object File-------------------------------------------

less /Test/test22.sic.obj
echo ----------------------------------------------------------------
echo Testing case 3  SIC Program Has  Invalid Hex Constant  
./project2 /Test/test23.sic
echo ----------------------------------------------------------------
echo Testing case 4  SIC Program HasSymbol Name that is an assembler Directive BYTE 
./project2 /Test/test24.sic
echo ----------------------------------------------------------------
echo Testing case 5  SIC Program Missing START DIRECTIVE   
./project2 test25.sic
less /Test/test25.sic.obj
echo ----------------------------------------------------------------
echo Testing case 6  Long Byte Constant that is ok   
./project2 /Test/test26.sic
echo ----------------------------------------------------------------
echo Testing case 7 
./project2 /Test/test27.sic
echo ----------TEST 27 Object File-------------------------------------------
less /Test/test27.sic.obj
echo ----------------------------------------------------------------
echo Testing case 8
./project2 /Test/test28.sic
echo ----------TEST 28 Object File-------------------------------------------
less /Test/test28.sic.obj
echo ----------------------------------------------------------------
echo Testing case 9   
./project2 /Test/test29.sic
echo ----------TEST 29 Object File-------------------------------------------
less /Test/test29.sic.obj
echo ----------------------------------------------------------------
echo Testing case 10  
./project2 /Test/test30.sic
echo ----------TEST 30 Object File-------------------------------------------
less /Test/test30.sic.obj

